apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component-sample-dec6-1
  namespace: maysun
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: application-sample-dec6-1
        appstudio.openshift.io/component: component-sample-dec6-1
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-sample-dec6-1-
      labels:
        appstudio.openshift.io/application: application-sample-dec6-1
        appstudio.openshift.io/component: component-sample-dec6-1
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: maysun
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-java-springboot-basic
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:maysun-component-sample-dec6-1-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:9f5d549dd64aacf10e3baac90972dfd5df788324
        name: docker-build
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
